### ISSUE TITLE
Congratulations and question

### ISSUE THREAD

**Issue by frederikhors** [azzamsa/tin#1]
Thank you for your project. It's really inspiring to see such a beautiful code. Thanks again.

One question:

I have a similar code architecture in my project. But I'm struggling with db transactions and different databases changed at runtime.

I see you're passing `DB` directly in services:

```rust
pub struct Repository {}

pub struct Service {
    repo: Repository,
    pub db: DB,
}
```

with DB:

```rust
use sqlx::{self, Executor, Pool, Postgres, Transaction};

pub type DB = Pool<Postgres>;

pub trait Queryer<'c>: Executor<'c, Database = sqlx::Postgres> {}

impl<'c> Queryer<'c> for &Pool<Postgres> {}
impl<'c> Queryer<'c> for &'c mut Transaction<'_, Postgres> {}
```

I can understand why: you can create transactions in services directly using something like:

```rust
let mut tx = pool.begin().await?;

// use tx

tx.commit().await?;
```

and even if this is not exactly what the Clean Architecture prescribes IMO (the services level goes into the details of persistence which is one level below) let's say I could accept it for "practicity of writing daily code".

But what I can't figure out is what I should change in the code to have at runtime the choice whether to persist on postgresql or sqlite for example.

Much difficult projects I have seen has a lot of traits in the service layer to describe the repository behavior. 

And those traits are implemented both for Postgresql's repository and Sqlite's one. Does it make sense to you?

Can you show in a separate branch (so I can easily spot differences with git diff) what to change to start app either with Postgresql or sqlite?

Thank you very much in advance and congratulations again for this amazing project!

**Comment by frederikhors** [comment]
I just realized that of course `sqlx` can use `sqlite` as well. Obviously I'm referring to a different repository, without sqlx.

For example an usage with MongoDB.

I imagine we need to have two directories under `repositories`:

- repositories:
  - postgres
    - mod.rs
  - mongo
    - mod.rs

And then?

**Comment by azzamsa** [comment]
Hi.

>  But I'm struggling with db transactions and different databases changed at runtime.

I never implemented such a feature.

>  I could accept it for the "practicality of writing daily code".

Yes. As described in the readme. This code follows Kerkour's version of "clean code". [Article](https://kerkour.com/rust-web-application-clean-architecture), [Code](https://github.com/skerkour/bloom-legacy/tree/v2-e2ee).

---

Regarding https://github.com/skerkour/bloom-legacy/issues/70#issuecomment-1627652473. Maybe you can ask him via email. He replied to my email once.

I saw many of your effort such as [Clean architecture and DB transactions in the same DDD bounded context? · Issue #203 · LukeMathWalker/zero-to-production](https://github.com/LukeMathWalker/zero-to-production/issues/203). I hope you can solve this clean code issue because it is harder to implement in Rust than in other languages.

**Comment by avucic** [comment]
@frederikhors path led me here with the same idea:) Have you found a solution so far?
